# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20170214_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='timestamp',
        ),
    ]
