# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20170214_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
